# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BibleTracker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BibleTracker
  pod 'ReachabilitySwift'
  pod 'NVActivityIndicatorView', '4.8.0'
  pod 'AnimatedCollectionViewLayout'
  pod 'FirebaseAnalytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Performance'
  pod 'Firebase/Crashlytics'

end
